### ISSUE TITLE
An error in the "HVDll.pas" unit, which causes the code to hang

### ISSUE THREAD

**Issue by DVK251** [pult/dll_load_delay#1]
Hi! I found a bug in the unit "HVDll.pas". In the "SysErrorMessage" function, the extra semicolon on line 587 (`{$ENDIF};`) causes the `Dec(Len)` operation on the next line is not executed and the While loop to become infinite (the program simply hangs at this point).

In addition, the module "HVDll.pas" does not compile when the `_MINI_` conditional define is turned off (if you comment out the corresponding definition on line 35). The error occurs in the TDlls.Destroy procedure because the FCount and FList fields of the TList class are not available. I suggest replacing:
line 957 (`for i := FCount-1 downto 0 do`) with `for i := {$IFDEF _MINI_}FCount{$ELSE}Count{$ENDIF} - 1 downto 0 do`
line 960 (`FList^[i] := nil;`) with `{$IFDEF _MINI_}FList{$ELSE}List{$ENDIF}^[i] := nil;`

**Comment by pult** [comment]
Thanks! Fixed: https://github.com/pult/dll_load_delay/commit/32697aad72544d8b9351d4d12eac1fc94d589765
