### ISSUE TITLE
The "aa90a83" version is not compiled in Delphi 7

### ISSUE THREAD

**Issue by DVK251** [pult/dll_load_delay#2]
Hi. After recent changes, the project stopped compiling out of the box in Delphi 7. In the "HVHeaps.pas" module, line 53, the conditional definition 
```   
    {$IF CompilerVersion >= 25.00} //# XE4_UP
      {$undef allow_inline} { no change }
    {$ELSE}
    {$IFEND}
``` 
should be replaced with
```
    {$IF CompilerVersion >= 18.00} //# D2006_UP
    {$ELSE}
      {$undef allow_inline}
    {$IFEND}
```
A similar conditional definition is also present in the file "HVDll.pas", line 79 - it is worth moving `{$undef allow_inline}` after the `{$ELSE  !UNICODE}` condition. 
In the same file "HVDll.pas", in line 830 with the call to the `MessageBoxA` function, there is an extra "}" character, which also causes a compilation error.

**Comment by pult** [comment]
Please recheck in now version [7545](https://github.com/pult/dll_load_delay/commit/50ba9dd115276fa4bf6c39cbc3dc10dd7e29185d)

**Comment by DVK251** [comment]
It is still not compiled until the directive `{$undef allow_inline}` is inserted into the file "HVHeaps.pas" in line 56 (between existing `{$ELSE}` and `{$IFEND}`)

**Comment by pult** [comment]
Thanks. HVHeaps fix https://github.com/pult/dll_load_delay/issues/2#issuecomment-1905440586
